### PR TITLE
Update to Plone 6.0.0b2 and pip 22.2.2

### PR DESCRIPTION
**Pull request by davisagli**

### CODE REVIEW

**Comment by stevepiercy** [comment]
After merge, `plone/documentation` also needs to be updated globally. Unfortunately there is no way to have a global substitution for this because almost all instances are in code blocks.

**Comment by davisagli** [comment]
@stevepiercy This might be a way to do a global substitution in Sphinx that includes the content of code blocks: https://stackoverflow.com/a/56328457

**Review by Rudd-O — APPROVED** [review]
LGTM.  The docs update comment you mentioned should not be forgotten.

**Comment by Rudd-O** [comment]
@davisagli please add the Towncrier update.

**Comment by davisagli** [comment]
@Rudd-O This repository does not have a changelog and is not using towncrier. The "changelog verifier" check is one that is enabled for all repositories in the plone organization, I think. I guess we need to find a way to turn it off for the repositories that don't require it.

**Comment by stevepiercy** [comment]
@davisagli it does not completely. We can either use `parsed-literal` and have no syntax highlighting, or we can have syntax lighting in a `code-block`, but not both.

We could post-process the HTML, but it takes just about as much effort and care as doing a global find and replace.

**Comment by stevepiercy** [comment]
Oh, wait a minute, maybe it could. This looks like a pre-processor. I was looking at the accepted answer.

**Comment by stevepiercy** [comment]
Yup, it works. I'll handle the PR after dinner. Thank you!

**Pull request merged**
