### PR TITLE
Add images for 6.0.0a3 and 5.2.7

### PR DESCRIPTION
**Pull request by sneridagh**

### CODE REVIEW

**Comment by sneridagh** [comment]
@mauritsvanrees did 6.0.0a3 already depends on `plone.volto`? We are adding it later in the image. 

Also, @avoinea @ericof @jensens @silviot Do we want to maintain all of them or deprecate (or just stop building) the images at some point (and rely on the historic from registry).

**Comment by mauritsvanrees** [comment]
> @mauritsvanrees did 6.0.0a3 already depends on `plone.volto`? We are adding it later in the image.

Not yet. We should probably do that for the next alpha (or first beta). The collective.folderishcontenttypes dependency is gone, which was the biggest blocker for this, IIRC.
PR is already here: https://github.com/plone/Plone/pull/20
But it would be good to fix some coredev tests first, which appear when we add plone.volto to the test eggs: https://github.com/plone/buildout.coredev/pull/764

**Comment by mauritsvanrees** [comment]
BTW, `pip` version 22 is out, which means we no longer need to use the deprecated resolver option.
But it gives a [problem with buildout](https://github.com/plone/buildout.coredev/pull/770) so it may be too much trouble to update currently.

**Review by ericof — APPROVED** [review]
LGTM

**Comment by jensens** [comment]
we need to upgrade to mxdev 2 with pip 22 here

**Comment by jensens** [comment]
pip 22 works fine in a3. I use it in a project (with mxdev 2)

**Comment by avoinea** [comment]
@jensens Should we then upgrade?

https://github.com/plone/plone-backend/blob/c066c7392ff67c43fb318c9aa7def0d91bfceed4/6.0/6.0.0a3/Dockerfile.python39#L19-L20

**Comment by jensens** [comment]
> @jensens Should we then upgrade?
> 
> https://github.com/plone/plone-backend/blob/c066c7392ff67c43fb318c9aa7def0d91bfceed4/6.0/6.0.0a3/Dockerfile.python39#L19-L20

Yes, pip 22 works fine with Plone and without the legacy resolver! 
But it should reflect in buildout.coredev pip pins (versions.cfg/requirements.cfg) as well then, right?

**Comment by mauritsvanrees** [comment]
> But it should reflect in buildout.coredev pip pins (versions.cfg/requirements.cfg) as well then, right?

I tried latest pip in coredev a few days ago, but it [failed](https://github.com/plone/buildout.coredev/pull/770).
I updated my WIP PR with the newest versions, but still fails.
Needs a fix in [buildout](https://github.com/buildout/buildout/issues/598)

BTW, `pip` 22.0.3 is out with a another [fix by me](https://github.com/pypa/pip/pull/10867) for the new resolver. Should only matter in corner cases.

**Comment by jensens** [comment]
ah, buildout, I use it with pip only in some projects and that works.

**Pull request merged**
