### PR TITLE
Image for 6.1.0b1

### PR DESCRIPTION
**Pull request by mauritsvanrees**
I have created branch 6.1.x as simple copy of 6.0.1, and have now created a branch to use 6.1.0b1, which I have just tagged and released on dist.plone.org.

I might very well overlook stuff that needs to be done for a first Docker release in the 6.1.x series.

Also, we may need to come up with a better way to show the table of latest releases: when we do a 6.0.14 release, it would be tedious to have to update both the 6.0.x and 6.1.x branches.

### CODE REVIEW

**Review by davisagli — CHANGES_REQUESTED** [review]
We should also:
- change the default branch to 6.1.x so that the nightly build uses this
- configure branch protection for the 6.1.x branch
- update the release.yml action so that it only sets IS_LATEST for the correct release series (6.0.x until we have a final release of 6.1)

**Comment by davisagli** [comment]
The test failed trying to run the `plone.volto:default-homepage` profile which doesn't exist any longer in Plone 6.1. I didn't look for where this comes from yet, but it probably should be updated to install the default distribution instead.

**Review by fredvd — APPROVED** [review]
Great!

**Comment by fredvd** [comment]
Hmm waiti. There’s a testing errror.  When create-site runs. The plone.volto:default-homepage has a problem.  Ah David noted it already as well.

**Comment by mauritsvanrees** [comment]
> We should also:
> 
> * change the default branch to 6.1.x so that the nightly build uses this

Yes (though I don't use the nightly).  We can do this after this PR actually works and is merged and released.

> * configure branch protection for the 6.1.x branch

Done.

> * update the release.yml action so that it only sets IS_LATEST for the correct release series (6.0.x until we have a final release of 6.1)

Done.

**Comment by mauritsvanrees** [comment]
> The test failed trying to run the `plone.volto:default-homepage` profile which doesn't exist any longer in Plone 6.1. I didn't look for where this comes from yet, but it probably should be updated to install the default distribution instead.

This comes from the [`create_site.py` script](https://github.com/plone/plone-backend/blob/6.1.x/skeleton/scripts/create_site.py) in the skeleton.
I have now updated this to use distributions.  This is adapted from the [script for demo.plone.org](https://github.com/plone/demo.plone.org/blob/main/backend/scripts/create_site.py).  I tried to keep supporting the old options, as otherwise we may need to change some documentation somewhere.  But the script no longer looks for an OS env `ADDITIONAL_PROFILES`.  So docs may need to be changed anyway.

I did not try the new script myself, nor build the image locally.  The tests now [fail at `plone-basics`](https://github.com/plone/plone-backend/actions/runs/11637987479/job/32412062204?pr=151#step:11:74).  I don't know what this is.

I quit for today, and likely this weekend.

**Comment by fredvd** [comment]
I have tried to replicate the failing lests by trying to run the test suite locally, but are there any requirements for an OS and/or bash version?  When I run this on a Mac with Bash 5 (make build-images, then use /test/run.sh)  I see several errors before the test suite components even  start. Then I do see the plone-basics tests hanging.

the main run.sh script also seeems to have regressions, for examlpe `run./sh -t utc plone/plone-backend:6.0.13` runs all tests, where -t utc should according to the README only run the utc test.

**Comment by fredvd** [comment]
Confirmed that the test suite should be run in recent (Ubuntu) linux only, it runs fine for plone-backend 6.0.13 when I build locally in an Ubuntu 22.04 VM. (using Vmware Fusion on Mac).  Now lets test with this branch.

**Comment by davisagli** [comment]
@fredvd @mauritsvanrees The new distributions-based launch page has different text than what the tests were checking for. I updated the tests, let's see how it goes. I also can't easily run the tests locally since they use some bash features that I don't have on macOS.

**Comment by davisagli** [comment]
@mauritsvanrees Thanks for working on the site creation script. I'd like to keep support for ADDITIONAL_PROFILES if possible, by running the profiles separately after installing the distribution. I'll try to add this next...

**Comment by fredvd** [comment]
> I also can't easily run the tests locally since they use some bash features that I don't have on macOS.

I updated my bash on my mac to 5 using homebrew and use jt as the default in my Terminals/iTerm2.  , but it still seems very different from the bash 5 in Ubuntu.

**Comment by davisagli** [comment]
@mauritsvanrees @fredvd There we go!

**Review by davisagli — APPROVED** [review]

**Comment by mauritsvanrees** [comment]
Nice!

**Comment by davisagli** [comment]
@fredvd Is there a reason we didn't create the 6.1.0b1 tag to trigger the image builds yet?

**Comment by fredvd** [comment]
A reason: No not really, I merged this branch after all feedback was taken into account and I ran the workflow manually on the 6.1.x to test the image with the things we fixed here.  But I  didn't continue or finish the release after that.  

I do see now docker description was also triggered maybe from the testing workflow, that's a bit odd.

**Comment by davisagli** [comment]
@fredvd Okay. I pushed the tag.

**Pull request merged**
