### PR TITLE
Install correct setuptools version through constraints.txt, Refs #112

### PR DESCRIPTION
**Pull request by fredvd**

### CODE REVIEW

**Review by davisagli — APPROVED** [review]
LGTM. Since PIP_VERSION was set using ENV rather than ARG, we don't need to worry about backwards compatibility with someone overriding it.

**Comment by fredvd** [comment]
> LGTM. Since PIP_VERSION was set using ENV rather than ARG, we don't need to worry about backwards compatibility with someone overriding it.

Ah good point.  I checked but we inject it indeed nowhere from outside the Dockerfile. For that it should have been an ARG. 


that ARG already tripped me over where it stayed undefined, because you have to insert it again after every FROM multi stage build switch.  Looks funny in the Dockerfile.

**Comment by fredvd** [comment]
I’ll wait for @ericof to check this as well, it’s easter weekend, this isn’t in a hurry.

**Comment by davisagli** [comment]
Yeah, that has tripped me up before also.

**Review by ericof — APPROVED** [review]

**Pull request merged**
