### PR TITLE
Fix permissions when mounting data volume

### PR DESCRIPTION
**Pull request by avoinea**
See #14

### CODE REVIEW

**Review by silviot — COMMENTED** [review]
I like the strategy with `gosu` and the usage of `exec` to avoid creating an unnecessary extra process.

I'm a bit worried by the performance hit of running `find` on each startup of each container, unconditionally.

While I understand why it might be desirable to do this for `/data` it looks to me that the round on `/app` should be avoided. IMHO not having the user `plone` have permissions over `/app` is a feature, since it makes things a little bit more difficult for an attacker.

#14 does not mention `/app` either.

**Review by silviot — APPROVED** [review]
Thinking more about this I believe I realized we need to make sure the `plone` user has write access to `/app` because we don't ship the `pyc` files in the docker image.

**Comment by avoinea** [comment]
> While I understand why it might be desirable to do this for `/data` it looks to me that the round on `/app` should be avoided. IMHO not having the user `plone` have permissions over `/app` is a feature, since it makes things a little bit more difficult for an attacker.
> 
> #14 does not mention `/app` either.

@silviot  Well, we are within a virtualenv and before we were already running it with user plone:

https://github.com/plone/plone-backend/blob/e9696637a5e4abcd04708b483fb900f1926e23b0/6.0/6.0.0a1/Dockerfile.python37#L39-L46

Thus, I think it will crash at some point if we don't switch owner also to `/app`. This is done on image creation, thus performance shouldn't be an issue.

> I'm a bit worried by the performance hit of running `find` on each startup of each container, unconditionally.
> 

Within the entrypoint.sh (container startup) it looks only in /app/var_instance:

https://github.com/plone/plone-backend/blob/6abfec6df4cd2dd821037a2b5cbf09780a0f8d6f/6.0/6.0.0a1/skeleton/docker-entrypoint.sh#L9

`/app/var_instance`, which, btw, I don't know what it is :smile: @ericof ?!?

**Comment by avoinea** [comment]
> Thinking more about this I believe I realized we need to make sure the `plone` user has write access to `/app` because we don't ship the `pyc` files in the docker image.
> 
> Maybe we should include them. The uncompressed size is around 56M. Having `.pyc` files would grant a faster startup for two reasons: we could skip the `find` invocation this PR introduces, and we'd have the files already present with no need to recompile them.

@silviot It would be interesting to see how fast it is with compiled `pyc` vs. stripped one in order to trade size for speed :wink:

**Comment by ericof** [comment]
> `/app/var_instance`, which, btw, I don't know what it is smile @ericof ?!?
I created this dir, that is not shareable as a volume, to deal with a scenario where you would scale an app (with docker-compose) and get permission errors.

**Review by ericof — DISMISSED** [review]
LGTM

**Comment by jensens** [comment]
Thinking about have this ready for Openshift, where theres no fixed userid at all - it is random - this wont work I suppose. The storage is mounted with this random userid and /tmp is writable IIRC. So, we should have it work there.

**Comment by avoinea** [comment]
@jensens Any easy way to test it on Openshift?

**Comment by pnicolli** [comment]
@cekk might be of help regarding Openshift

**Comment by cekk** [comment]
@avoinea sure: use minishift ;) 

https://docs.okd.io/3.11/minishift/index.html

**Comment by avoinea** [comment]
@cekk @jensens 

minishift didn't work on my machine (archlinux, some conflicts with my VPN setup) does not work on a fresh hetzner machine. As I already spent too many hours on it and as I don't use openshift and don't plan to use it in the near future, I give up.

If someone has an OpenShift setup and can give it a try, please do, otherwise let's add a ticket and move on.

**Comment by avoinea** [comment]
Ok, this may solve the random user use case: https://github.com/plone/plone-backend/pull/18

**Comment by avoinea** [comment]
Ok, many hours later, minishift is up-and-running :). And indeed, the current image on Docker Hub fails with:
```
mkdir: cannot create directory ‘/app/var_instance’: Permission denied
```

Thus, we need to get rid of this folder first. I'll prepare another PR.

**Comment by avoinea** [comment]
I added tests to Github actions. It seems they already catched something on `Python 37 Plone 5.2.6`

**Comment by ericof** [comment]
Did you test scaling the number of containers AND sharing the data volume?

**Review by ericof — APPROVED** [review]
LGTM

**Pull request merged**
