### PR TITLE
Added development capability

### PR DESCRIPTION
**Pull request by pnicolli**
I think this implementation is simple enough to be worth adding to these base images in order to be available for anyone whether they use the base image to develop a single package or extend the image. Let me know if you think this should be achieved in another way.

Of course the change to the entrypoint needs to be copied over to other image skeletons before merging, and it needs more testing because I can't test it in a proper way since I'm on a train at this time :)

### CODE REVIEW

**Review by avoinea — APPROVED** [review]
@pnicolli I think this is already achievable via `ADDONS` env, like:

```
docker run -it --rm -v $(pwd):/app/my.addon -e ADDONS="--editable /app/my.addon[test]" plone/plone-backend 
```
But yes, I'm in favor of having an env dedicated for this purpose :+1: 

Also, I wonder if we can move `${PIP_PARAMS}` after `install`, this way we would be able to pass `--editable` via `PIP_PARAMS`

@ericof Thoughts?!

**Comment by pnicolli** [comment]
It's probably achievable with ADDONS as you say, but can you also achieve something like installing a few addons and developing another addon? For example if I want to install ``collective.easyform`` and develop my own addon, can I do that with just ADDONS?

**Comment by ericof** [comment]
I like @pnicolli's approach, but we need to consider the following:

- [ ] Do we need a volume (pointing to /app/src/)?
- [ ] How do we proper document that?

**Comment by pnicolli** [comment]
Oops, I had actually wrote the README part for my addition but I see it's not present in the PR. I wrote it on the train and I might have had issues with the network, let me push that again as an example of how I would document that.

**Comment by ericof** [comment]
@pnicolli, Could you replicate that to the other images? Then I will merge and push to docker hub

**Review by ericof — DISMISSED** [review]
Just modify the entrypoint on other images and we are good to go

**Comment by pnicolli** [comment]
@ericof done!

**Review by avoinea — APPROVED** [review]

**Pull request merged**
