### PR TITLE
Testing multiarch builds

### PR DESCRIPTION
**Pull request by sneridagh**

### CODE REVIEW

**Comment by sneridagh** [comment]
Mmm the test does not find the tag, could be that it tagged it differently now? The builds seem to be generated correctly for each platform.

**Comment by sneridagh** [comment]
hehe, almost there :)

It seems that the `load: true` only work on single-platform builds. So you need to do the tests with half of the build, then trigger the multipart.

However, WTF, it fails on Python 3.7 building the wheel for Pillow? and in the others do not?

**Comment by sneridagh** [comment]
ok... weirdly enough, locally I can reproduce it...

**Comment by sneridagh** [comment]
@fredvd @tisto did you mention you had some problems with Python 3.7 in arm64, right? Related to Pillow?

**Comment by sneridagh** [comment]
I guess that the good news is that it works well with latest versions of Pillow, eg. used in Plone 6. Using pillow==6.2.2 breaks in python 3.7 (and in 3.6 or 3.8 works well! 🤦 )  :(

**Comment by jensens** [comment]
Oh, the I-need-old-Pillow/ARM64  problem. But Do we need to support Python 3.7 at all here? I have no idea who would need it in a docker container.

**Comment by jensens** [comment]
My serious question is, isn't it enough to support the latest supported (by Plone) version of Python for our backend?

**Comment by sneridagh** [comment]
@jensens I agree... what's the point for supporting three Python versions? If inside a container it has any sense? Shouldn't be sufficient with one (highest)?

**Comment by jensens** [comment]
I'll bring up this question on community.plone.org to get some feedback if we might have missed a use-case.

**Comment by avoinea** [comment]
I don't have a strong opinion on supporting multiple python versions. Thus I'm ok with dropping them and stick to one.

**Comment by jensens** [comment]
https://community.plone.org/t/docker-image-plone-backend-and-python-versions/14673

**Review by jensens — APPROVED** [review]

**Pull request merged**
